base_path = '/home/santtedo/'
modelos_path = base_path + 'buckets/b1/modelos/'
db_path = base_path + 'buckets/b1/optimizacion/'
datasets_path = base_path + 'buckets/b1/datasets/'
exp_path = base_path + 'buckets/b1/exp/'
pred_path = base_path + 'buckets/b1/predicciones/'

dataset_file_crudo = datasets_path + 'competencia_02_crudo.csv.gz'
dataset_file_clase_ternaria = datasets_path + 'competencia_02_brandoni.csv.gz'

#6 meses
dataset_file_prepro_6 = datasets_path + 'competencia_02_brandoni_prepro_6.csv.gz'
dataset_file_prepro_6x = datasets_path + 'competencia_02_brandoni_prepro_6x.csv.gz'
dataset_file_fe6_6pqt = datasets_path + 'competencia_02_fe6_6.parquet'
dataset_file_fe6_6xpqt = datasets_path + 'competencia_02_fe6_6x.parquet'

# #9 meses
# dataset_file_prepro_9 = datasets_path + 'competencia_02_brandoni_prepro_9.csv.gz'
# dataset_file_fe6_9pqt = datasets_path + 'competencia_02_fe6_9.parquet'

# #12 meses
# dataset_file_prepro_12 = datasets_path + 'competencia_02_brandoni_prepro_12.csv.gz'
# dataset_file_fe3_12 = datasets_path + 'competencia_02_fe_12.parquet'

variables_x = [
    'active_quarter',
    'cliente_vip',
    'internet',
    'cliente_edad',
    'cliente_antiguedad',
    'mrentabilidad',
    'mrentabilidad_annual',
    'mcomisiones',
    'mactivos_margen',
    'mpasivos_margen',
    'cproductos',
    'tcuentas',
    'ccuenta_corriente',
    'mcuenta_corriente_adicional',
    'ccaja_ahorro',
    'mcaja_ahorro_adicional',
    'mcaja_ahorro_dolares',
    'cdescubierto_preacordado',
    'ctarjeta_debito',
    'ctarjeta_debito_transacciones',
    'mautoservicio',
    'ctarjeta_visa',
    'ctarjeta_visa_transacciones',
    'ctarjeta_master',
    'ctarjeta_master_transacciones',
    'cprestamos_personales',
    'mprestamos_personales',
    'cprestamos_prendarios',
    'mprestamos_prendarios',
    'cprestamos_hipotecarios',
    'mprestamos_hipotecarios',
    'cplazo_fijo',
    'mplazo_fijo_dolares',
    'mplazo_fijo_pesos',
    'cinversion1',
    'minversion1_pesos',
    'minversion1_dolares',
    'cinversion2',
    'minversion2',
    'cseguro_vida',
    'cseguro_auto',
    'cseguro_vivienda',
    'cseguro_accidentes_personales',
    'ccaja_seguridad',
    'cpayroll_trx',
    'mpayroll2',
    'cpayroll2_trx',
    'ccuenta_debitos_automaticos',
    'mcuenta_debitos_automaticos',
    'ctarjeta_visa_debitos_automaticos',
    # 'mtarjeta_visa_debitos_automaticos', # rompe el comp02_fe6_6x
    'ctarjeta_master_debitos_automaticos',
    'mttarjeta_master_debitos_automaticos',
    'cpagodeservicios',
    'mpagodeservicios',
    'cpagomiscuentas',
    'mpagomiscuentas',
    'ccajeros_propios_descuentos',
    'mcajeros_propios_descuentos',
    'ctarjeta_visa_descuentos',
    'mtarjeta_visa_descuentos',
    'ctarjeta_master_descuentos',
    'mtarjeta_master_descuentos',
    'ccomisiones_mantenimiento',
    'ccomisiones_otras',
    'cforex',
    'cforex_buy',
    'mforex_buy',
    'cforex_sell',
    'mforex_sell',
    'ctransferencias_recibidas',
    'mtransferencias_recibidas',
    'ctransferencias_emitidas',
    'mtransferencias_emitidas',
    'cextraccion_autoservicio',
    'mextraccion_autoservicio',
    'ccheques_depositados',
    'mcheques_depositados',
    'ccheques_emitidos',
    'mcheques_emitidos',
    'ccheques_depositados_rechazados',
    'mcheques_depositados_rechazados',
    'ccheques_emitidos_rechazados',
    'mcheques_emitidos_rechazados',
    'tcallcenter',
    'ccallcenter_transacciones',
    'thomebanking',
    'chomebanking_transacciones',
    'ccajas_transacciones',
    'ccajas_consultas',
    'ccajas_depositos',
    'ccajas_extracciones',
    'ccajas_otras',
    'catm_trx',
    'matm',
    'catm_trx_other',
    'matm_other',
    'ctrx_quarter',
    'tmobile_app',
    'cmobile_app_trx',
    'Master_delinquency',
    'Master_status',
    'Master_mfinanciacion_limite',
    'Master_Fvencimiento',
    # 'Master_Finiciomora', # data drifting
    'Master_msaldototal',
    'Master_msaldopesos',
    'Master_msaldodolares',
    'Master_mconsumospesos',
    'Master_mconsumosdolares',
    'Master_mlimitecompra',
    'Master_madelantopesos',
    'Master_madelantodolares',
    # 'Master_fultimo_cierre', # data drifting
    'Master_mpagado',
    'Master_mpagospesos',
    'Master_mpagosdolares',
    'Master_fechaalta',
    'Master_mconsumototal',
    'Master_cconsumos',
    'Master_cadelantosefectivo',
    'Master_mpagominimo',
    'Visa_delinquency',
    'Visa_status',
    'Visa_mfinanciacion_limite',
    'Visa_Fvencimiento',
    # 'Visa_Finiciomora', # data drifting
    'Visa_msaldototal',
    'Visa_msaldopesos',
    'Visa_msaldodolares',
    'Visa_mconsumospesos',
    'Visa_mconsumosdolares',
    'Visa_mlimitecompra',
    'Visa_madelantopesos',
    'Visa_madelantodolares',
    # 'Visa_fultimo_cierre', # data drifting
    'Visa_mpagado',
    'Visa_mpagospesos',
    'Visa_mpagosdolares',
    'Visa_fechaalta',
    'Visa_mconsumototal',
    'Visa_cconsumos',
    'Visa_cadelantosefectivo',
    'Visa_mpagominimo',
]
